language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install pytest coverage pytest-cov codecov
  - pip install -r requirements.txt
script: 
  - py.test --cov-report term --cov=Jobtimize test/
after_success:
  - codecov